"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 1.8.18.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import sys
from django.conf.urls import url, include
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(BASE_DIR+"/packages")
sys.path.append(BASE_DIR+"/packages/django")
import argo
# import django

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'bw(lu4t*o&*ot4&gf^&74ksjz3r+ji6bxr_9$y0sacg*ks0m0w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
# Application definition

INSTALLED_APPS = (
    'permission_backend_nonrel',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)
AUTHENTICATION_BACKENDS = (
    'permission_backend_nonrel.backends.NonrelPermissionBackend'
)
MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'django.middleware.security.SecurityMiddleware',
)



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
SESSION_EXPIRE_AT_BROWSER_CLOSE=True
WSGI_APPLICATION = 'wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
DATABASES = {
   'default' : {
       'ENGINE' : 'django_mongodb_engine',
       'NAME' : 'hrm',
       'HOST':'localhost',
       'PORT':27017,
       'USER':'root',
       'PASSWORD':'123456'
   }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME':os.path.join(os.getcwd(), 'database','db.sqlite3'),
#     }
# }


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = False

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
APPS=[dict(host="default",
           name="argo",
           path="apps/app_main"),
      dict(host="admin",
           name="admin",
           path="apps/admin"),
      dict(host="hrm",
           name="hrm",
           path="apps/hrm")]
aut_config_local=dict(
    provider="authorization.auth",
    name="lv01_lms",
    host="localhost",
    port=27017,
    _user="sys",
    _password="123456"
)
argo.authorization.load(aut_config_local)

membership_config_local=dict(
    provider="membership_mongo",
    name="lv01_lms",
    host="localhost",
    port=27017,
    _user="sys",
    _password="123456",
    elasticsearch=["http://localhost:9200"]
)
argo.membership.load(membership_config_local)
language_congig_local=dict(
provider="language_mongo_engine",
    name="lv01_lms",
    host="localhost",
    port=27017,
    _user="sys",
    _password="123456",
    collection="sys_languages"
)
argo.language.load(language_congig_local)

AUTHORIZATION_ENGINE=argo.authorization
MEMBERSHIP_ENGINE=argo.membership
LANGUAGE_ENGINE=argo.language

argo.url.build_urls("apps",APPS)
ROOT_URLCONF = 'apps'

# STATIC_ROOT = os.path.join(*(BASE_DIR.split(os.path.sep) + ['apps/static','apps/app_main/static']))